### ISSUE TITLE
Support for reading .jsinspectrc

### ISSUE THREAD

**Issue by paazmaya** [stefanjudis/grunt-jsinspect#10]
As the `jsinspect` command line version does, it checks the existence of `.jsinspectrc` and uses it for any configuration options that are not provided via command line.

Currently it would duplicate code, so opening another issue at https://github.com/danielstjules/jsinspect/issues/9

**Comment by szarouski** [comment]
:+1:

**Comment by paazmaya** [comment]
Uh.... already many months.
I need to check all my different computers so that I would not accidentally have it anywhere locally.
