### ISSUE TITLE
ignore option for grunt-jsinspect doesn't seem to work.

### ISSUE THREAD

**Issue by parsana** [stefanjudis/grunt-jsinspect#26]
I can't figure out how to ignore a file or folder using grunt-jsinspect.  I can do it using the command line but I can't get it to work using the jsinspect grunt options.

**Comment by yeahoffline** [comment]
use the src array with a starting !
like:
```
grunt.initConfig({
  jsinspect: {
    examples: {
      options: {
        threshold:   30,
        diff:        true,
        identifiers: false,
        failOnMatch: true,
        suppress:    100,
        reporter:    'default'
      },
      src: [
        '**/*.js',
        '!**/node_modules/**'
      ]
    }
  }
});

```

see: http://gruntjs.com/api/grunt.file#grunt.file.expand

**Comment by stefanjudis** [comment]
@yeahoffline thanks for jumping...

I kind of missed this one. :)

**Comment by yeahoffline** [comment]
yw

**Comment by stefanjudis** [comment]
Good idea. :+1:
