### ISSUE TITLE
Add support for options.jsx

### ISSUE THREAD

**Issue by paazmaya** [stefanjudis/grunt-jsinspect#31]
I can make a PR :corn:

**Comment by paazmaya** [comment]
This should land before `1.0.0`... if possible

**Comment by paazmaya** [comment]
Targeting `1.1.0` with this feature.

**Comment by stefanjudis** [comment]
Adding functionality -> minor version bumb. Nice. :+1:

**Comment by paazmaya** [comment]
Feature documented and taken in master 41448b5aeb236200bb49b2a59eebd9b8343aaac3

**Comment by stefanjudis** [comment]
:+1: 

Whooops - let's follow commit convention `... - fix #123` for the next time?

**Comment by paazmaya** [comment]
Will "try" to keep it in mind...

**Comment by stefanjudis** [comment]
:+1:
