### ISSUE TITLE
Ability to skip 'the following section'

### ISSUE THREAD

**Issue by jonbcampos** [stefanjudis/grunt-jsinspect#33]
Similar to istanbul it would be nice to skip sections with code inserts. In my angularjs app many of the modules start with a similar 'imports' section and they are all stating they are duplicates. Yes they are, but I accept these sections and would like to focus on the meat and potatoes

**Comment by stefanjudis** [comment]
Is this a feature provided by jsinspect itself?

If not it should go there first. :bowtie:

**Comment by jonbcampos** [comment]
Duh. Good point. I will check and update

**Comment by jonbcampos** [comment]
added
https://github.com/danielstjules/jsinspect/issues/27

**Comment by stefanjudis** [comment]
:bowtie:
