### ISSUE TITLE
outputPath does not create intermediate folders

### ISSUE THREAD

**Issue by wingedfox** [stefanjudis/grunt-jsinspect#34]
Providing
```
outputPath: target/reports/jsinspect/output.xml'
```
I need to create all intermediate folders prior to run of the task, because
```
 fs.createWriteStream(options.outputPath, {encoding: 'utf8', flags: 'w'});
```
does not create them internally and always fails with 
```
Fatal error: ENOENT, open 'target/reports/jsinspect/output.xml'
```

This is a side-effect of execution of
```
inspector.run();
```
without prior check for success stream open.
I suggest to fix that the following way
```
    if (writableStream) {
      writableStream.on('finish', function() {
        done(taskSucceeded);
      });
      writableStream.on('open', function() {
        inspector.run();
      });
    } else {
      inspector.on('end', function() {
        done(taskSucceeded);
      });
      inspector.run();
    }
```
and process  writableStream.on('error' for early error reporting.

**Comment by paazmaya** [comment]
Would you suggest that the plugin would use something similar to `mkdir -p` ?

**Comment by wingedfox** [comment]
Yes, http://gruntjs.com/api/grunt.file#grunt.file.mkdir works fine for me.

**Comment by paazmaya** [comment]
@stefanjudis how about adding this for `v1.1.0` ?

**Comment by stefanjudis** [comment]
:+1: 

@wingedfox Maybe wanna PR? :)

**Comment by stefanjudis** [comment]
Fixed with 

https://github.com/stefanjudis/grunt-jsinspect/pull/37
