### ISSUE TITLE
Master is missing the 1.0.0 tag

### ISSUE THREAD

**Issue by paazmaya** [stefanjudis/grunt-jsinspect#35]
Seems that there is the tag for `v1.0.0` which also has the version in `package.json`, but this is not in `master`.
What might have happened @stefanjudis ?

**Comment by stefanjudis** [comment]
what do you mean - I see it directly in front of me?

**Comment by stefanjudis** [comment]
Should be fixed. Thanks for heads up.

**Comment by paazmaya** [comment]
Now is nice :grapes:
