### ISSUE TITLE
Minimum Node.js version to be 4.2.0 ?

### ISSUE THREAD

**Issue by paazmaya** [stefanjudis/grunt-jsinspect#41]
Shall we make it so?

Tests for `0.10` are failing since https://github.com/sindresorhus/grunt-eslint/blob/master/package.json#L13 is at least 4.

I see no reason to keep supporting less than LTS, 4.2.0.

**Comment by stefanjudis** [comment]
👍

**Comment by paazmaya** [comment]
Ok then, I will make it happen

**Comment by paazmaya** [comment]
```yml
before_script:
  - npm install -g npm
```

Can @stefanjudis recall why this was needed again for Travis CI?

Node.js 4.2.0 comes with 2.14.7 ...

**Comment by stefanjudis** [comment]
hmm... to guarantee the latest npm version, but yeah when it runs without this one, we can surely drop it. :)

**Comment by paazmaya** [comment]
Its green!

**Comment by stefanjudis** [comment]
Should I release it (or were you able to do so?)

**Comment by paazmaya** [comment]
I could try, shall it be `1.3.0` or `2.0.0` or `1.2.1`, just depends of what we consider dropping pre-4 being?

**Comment by stefanjudis** [comment]
well it's breaking right? So `2.0.0`? :)

**Comment by paazmaya** [comment]
Ok then!

**Comment by paazmaya** [comment]
https://www.npmjs.com/package/grunt-jsinspect
