### ISSUE TITLE
Update for jsinspect 0.10+?

### ISSUE THREAD

**Issue by danielstjules** [stefanjudis/grunt-jsinspect#42]
The release saw quite a few breaking changes, as noted here: https://github.com/danielstjules/jsinspect/releases/tag/0.10.0 Overall, the tool works _much better_ now :)

**Comment by paazmaya** [comment]
Sure thing, perhaps during the next few days

**Comment by paazmaya** [comment]
Hups, been busy with my mind and lost the memory of this..

PR of course welcome.. 🍇

**Comment by paazmaya** [comment]
Um, it is already at `0.12.6`, https://github.com/danielstjules/jsinspect/releases

**Comment by rhpijnacker** [comment]
@paazmaya: So, any chances of updating to `0.12.6` soon?
